# See: `starship print-config`
# See https://starship.rs/config/
# Custom symbols (which respect text color), replacing emojis, are from:
# https://starship.rs/presets/#nerd-font-symbols

add_newline = true
command_timeout = 5000

#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$all
#[â””â”€>](bold green) """

[aws]
symbol = "îŒ½ "

[battery]
disabled = true

[character]
success_symbol = "[â¯](bold blue)"  # [â¯](bold green) is default.  Could use [âœ]
error_symbol = ""  # Was [âœ—](bold red).  Replaced by status module

[cmd_duration]
#min_time = 2000
#disabled = false
show_notifications = true
#min_time_to_notify = 45000

[directory]
style = "bold blue"
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
#style = "bold red"
style = "bold black"
symbol = "ï˜ "

[git_status]
style = "bold black"
# `starship timings` says it takes 750 ms in git_status module.  Too slow!
disabled = true

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
disabled = true
symbol = "î‰ "

[package]
#disabled = true
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "  # default is ğŸ

[ruby]
symbol = "îˆ¾ "

[rust]
#symbol = "ï€“ "
symbol = "î¨ "

[scala]
symbol = "îœ· "

[status]
disabled = false
format = """
[$status $symbol]($style)"""

[swift]
symbol = "ï¯£ "

[username]
show_always = true
style_user = "bold green"

